[package]
name = "arrays_slices"
version = "0.1.0"
authors = ["etvanlieshout <ericvanl@buffalo.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
